EC-CUBE/eccube-api4

Resource/config/services.yaml
Grant を authorization code / refresh token grant に制限しました。
手元の API クライアントで Grant が制限されていることを確認しています。
- authorization code grant
- refresh token grant
- client credentials grant
- password grant
- implicit grant
`trikoder/oauth2-bundle` の 3.x 以降で code challenge for public clients が利用できるようです。
ただ、 Symfony 4.4 以上でしか動かないようですので EC-CUBE 4.1 で期待です。。。
https://github.com/trikoder/oauth2-bundle
=> Grant を authorization code / refresh token grant に制限

GraphQL/Types.php, Resource/config/services.yaml, Tests/GraphQL/TypesTest.php, Tests/Web/Admin/LoginControllerTest.php
以下のDBカラムを返さないように修正
- dtb_base_info.authentication_key
- dtb_customer.password
- dtb_customer.reset_key
- dtb_customer.salt
- dtb_customer.secret_key
- dtb_member.password
- dtb_menber.salt
#4
=> 機密性の高いフィールドはAPIから返さない

.travis.yml, Tests/Web/Admin/LoginControllerTest.php
プラグインのインストールがコマンドでのインストールとなるので `install_eccube` で `composer require trikoder/oauth2-bundle` してやることで回避しました。
=> .travis.yml を追加

Form/Type/Admin/ClientType.php
デフォルトで Refresh Token が有効になっていなかったので有効にしてClient作成できるように修正
close #23
=> デフォルトで Refresh Token を有効にしてClient作成

GraphQL/Type/Definition/DateTimeType.php, GraphQL/Types.php
close #27
DateTime を扱う `DateTimeType ` を独自に実装した。
日付のフォーマットは `DateTime::ATOM = "Y-m-d\TH:i:sP"` とした
https://www.php.net/manual/ja/class.datetimeinterface.php#datetime.constants.atom
> DateTimeInterface::ATOM
> Atom (例: 2005-08-15T15:52:01+00:00)
`DateTimeInterface::RFC3339_EXTENDED` でミリ秒まで返せるが、そもそもDBでミリ秒まで管理できていないので `000` となってしまうので対応していない。
▼参考にしたIssue
https://github.com/webonyx/graphql-php/issues/228#issuecomment-356957616
▼参考にしたドキュメント
https://webonyx.github.io/graphql-php/type-system/scalar-types/
request
```graphql
query getOrders {
products {
id
create_date
update_date
}
}
```
responce
```json
{
"data": {
"products": [
{
"id": "5",
"create_date": "2020-07-13T17:40:50+09:00",
"update_date": "2020-07-13T17:42:18+09:00"
},
{
"id": "4",
"create_date": "2020-07-07T16:26:18+09:00", …
```
=> 日付を取得できるようにした

DependencyInjection/Compiler/ApiCompilerPass.php
- fixes https://github.com/EC-CUBE/eccube-api4/issues/26
- https://github.com/EC-CUBE/ec-cube/pull/4625 と共に必要
=> プラグイン無効時にはConvertExceptionToResponseListenerを外す

DependencyInjection/Compiler/ApiCompilerPass.php
`ApiComplierPass:: generateKeys()` で気になる部分を対応しました。
- publicKey, privateKey生成時のディレクトリ・ファイルの生成に失敗した場合にExceptionを発生させる
- OpenSSL Supportがない環境も念の為考慮して `function_exists` でopenssl関数があるかをチェックさせた
=> OpenSSLの関数チェックとディレクトリ・ファイルが生成時のエラー処理の追加

Controller/ApiController.php, GraphQL/Type/ConnectionType.php, GraphQL/Type/Definition/DateTimeType.php, GraphQL/Type/EdgeType.php, GraphQL/Type/EdgesType.php, GraphQL/Type/PageInfoType.php, GraphQL/Types.php, Resource/config/services.yaml, Resource/locale/messages.en.yaml, Resource/locale/messages.ja.yaml
close #30 
ページング機能を追加しました。
既存のグラフ構造では実現が難しかったので大きく変更しています。
管理画面の検索機能と同様に `page`, `limit` のパラメータを指定することでページごとの取得が可能です。
最終的な実行例は以下のコメントを参照
https://github.com/EC-CUBE/eccube-api4/pull/32#issuecomment-660825380
<details>
Query例
```GraphQL
query {
products (page: "2", limit: "3") {
edges {
id
name
}
pageInfo {
totalCount
hasNextPage
hasPreviousPage
}
}
customers (page: "1", limit: "3", multi: "440", customer_status: ["3"]) {
edges {
id
name01
name02
}
pageInfo {
totalCount
hasNextPage
hasPreviousPage
}
}
}
```
Response例
```json
{
"data": {
"products": {
"edges": [
{
"id": "528",
"name": "河ぎんががらんとうについていままたために、向むこうように見えないところ、細ほそながら何がそのうし。"
},
{
"id": "527",
"name": "いながられたぬれた天の川の波なみちを、し。"
},
{
"id": "529",
"name": "の野原かわけられているか、あ。"
}
],
"pageInfo": {
"totalCount": 532,
"hasNextPage": true, …
```
=> paging の実装

Controller/ApiController.php, GraphQL/Error/FormInvalidException.php
close https://github.com/EC-CUBE/eccube-api4/issues/35
https://github.com/EC-CUBE/eccube-api4/pull/32 の続きで開発をしていますのでそちらを先に取り込みをお願いします。
差分が多く出ていますが、本件に関する修正点は最後のcommitだけです。
リゾルバ内で発生したエラーは情報漏洩を避けるために全て "Internal server error" となります。
Formでのバリデーションエラーは登録者に伝えるためのもので、レスポンスに含めても問題ないかと思います。
問題ないエラーであることを明確に定義するため FormInvalidException を定義して throw しています。
参考
https://webonyx.github.io/graphql-php/error-handling/#default-error-formatting
=> 検索条件のバリデーションエラーをレスポンスに返すように

GraphQL/Type/ConnectionType.php, GraphQL/Type/EdgeType.php, GraphQL/Type/PageInfoType.php
こちらのようになりました。
```graphql
type ProductConnection {
edges: [ProductEdge]
nodes: [Product]
pageInfo: ProductPageInfo!
totalCount: Int!
}
type ProductEdge {
node: Product
}
type ProductPageInfo {
hasNextPage: Boolean!
hasPreviousPage: Boolean!
}
```
=> Type名が冗長だったので短縮

DependencyInjection/Compiler/ApiCompilerPass.php, GraphQL/Query.php, GraphQL/Query/CustomersQuery.php, GraphQL/Query/OrdersQuery.php, GraphQL/Query/ProductsQuery.php, GraphQL/Schema.php, GraphQL/SearchFormQuery.php, Resource/config/services.yaml
`Plugin\Api\GraphQL\Query` インターフェイスを実装したクラスをコンテナに登録していれば、GraphQLに追加されるようにした。
=> Queryをプラグイン/カスタマイズで追加できるようにする

DependencyInjection/Compiler/ApiCompilerPass.php, GraphQL/Query.php, GraphQL/Query/CustomerQuery.php, GraphQL/Query/CustomersQuery.php, GraphQL/Query/OrderQuery.php, GraphQL/Query/OrdersQuery.php, GraphQL/Query/ProductQuery.php, GraphQL/Query/ProductsQuery.php, GraphQL/Query/SearchFormQuery.php, GraphQL/Query/SingleResultQuery.php, GraphQL/Schema.php, GraphQL/SearchFormQuery.php, Resource/config/services.yaml
#47 のコミットに続けてます。
以下のQueryを追加しました。
```
type Query {
product(id: ID!): Product
order(id: ID!): Order
customer(id: ID!): Customer
}
```
ref #34
=> ID指定でproduct/order/customerを取得するQueryを追加

Command/DumpSchemaCommand.php
指定したTypeだけを出力するようにしました。
```
$ bin/console eccube:api:dump-schema Product
type Product {
id: ID!
name: String!
note: String
description_list: String
description_detail: String
search_word: String
free_area: String
create_date: DateTime!
update_date: DateTime!
ProductCategories: [ProductCategory]
ProductClasses: [ProductClass]
ProductImage: [ProductImage]
ProductTag: [ProductTag]
CustomerFavoriteProducts: [CustomerFavoriteProduct]
Creator: Member
Status: ProductStatus
}
```
=> dump-schemaコマンドで指定したTypeのスキーマを出力するようにした

Service/CoreEntityTrigger.php
ジェネレータでデータ作成時に `$entity->getProductClass()` が未設定でflushされることがあり、イベントが発生してエラーが発生していたのでnullのチェックを追加した。
=> trigger データに不整合がある場合でもエラーが発生しないように修正

Controller/ApiController.php, GraphQL/ScopeValidationRule.php, Tests/Web/ApiControllerTest.php
`DocumentValidator` の仕組みを使ってscopeをチェックするようにしました。
https://webonyx.github.io/graphql-php/security/
ref #62
=> Scopeをチェックする

GraphQL/Mutation/UpdateProductStockMutation.php, GraphQL/Mutation/UpdateShippedMutation.php, GraphQL/Query/SearchFormQuery.php, GraphQL/Type/Definition/DateTimeType.php, Resource/locale/messages.en.yaml, Resource/locale/messages.ja.yaml, Tests/GraphQL/Mutation/UpdateShippedMutationTest.php, Tests/GraphQL/SchemaTest.php
close #39 
リクエスト例
```graphql
mutation UpdateShipped(
$id: ID!,
$shipping_date: DateTime,
$shipping_delivery_name: String,
$tracking_number: String,
$note: String,
$is_send_mail: Boolean
){
updateShipped (
id: $id,
shipping_date: $shipping_date
shipping_delivery_name: $shipping_delivery_name
tracking_number: $tracking_number
note: $note
is_send_mail: $is_send_mail
) {
id
shipping_delivery_name
shipping_delivery_date
shipping_date
tracking_number
note
mail_send_date
Order {
OrderStatus {
id
name
}
}
}
}
```
variables
```json
{
"id": 1576,
"shipping_date": "2020-05-18T12:57:08+09:00",
"shipping_delivery_name": "オレオレ配送業者",
"tracking_number": "tracking_number0123",
"note": "Hello Notes!",
"is_send_mail": true
}
```
レスポンス
```json
{
"data": {
"updateShipped": {
"id": "1576", …
```
=> 出荷情報を出荷済みに変更するMutationの実装

Resource/config/services.yaml
[EC-CUBEのディレクトリ構成](https://doc4.ec-cube.net/plugin_spec#%E3%81%9D%E3%81%AE%E4%BB%96%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB)に従って `app/PluginData` 以下にしました。
=> デフォルトの鍵保管場所を変更

docs/_pages/mutation/product_stock.md
refs https://github.com/EC-CUBE/eccube-api4/issues/38
refs https://github.com/EC-CUBE/eccube-api4/pull/50
=> 商品在庫の更新のドキュメントを追加

EventListener/AuthorizationRequestResolveListener.php, Form/Type/Admin/OAuth2AuthorizationType.php, Resource/locale/messages.en.yaml, Resource/locale/messages.ja.yaml, Resource/template/admin/OAuth/authorization.twig, Tests/Web/Admin/OAuth2Bundle/AuthorizationControllerTest.php
- デザインを調整しました
- 「許可しない」を選んだ場合は、仕様に従って[エラーレスポンス](https://openid-foundation-japan.github.io/rfc6749.ja.html#rfc.section.4.1.2.1)(error=access_denied)をコールバックURLに返すようにしました
ref #44
=> 認可リクエスト画面の改善

Controller/Admin/OAuthController.php, Form/Type/Admin/ClientType.php, Resource/locale/messages.en.yaml, Resource/locale/messages.ja.yaml, Resource/template/admin/OAuth/edit.twig, Resource/template/admin/OAuth/index.twig, Tests/Web/Admin/OAuthControllerTest.php
OAuth管理画面を改善しました。
- クライアントを登録時にScopeとGrantを選択できるようにしました。 close #62
- 各項目にツールチップを設定しました。
- 一覧画面でIDとSecretをコピーできるようにしました。 close #61
Secretを全く非表示にするのは大変だったので、妥協しています。（フォームを非表示にするとコピーできない）
=> OAuth管理画面の改善

GraphQL/Query/SearchFormQuery.php, GraphQL/Type/Definition/DateTimeType.php, Tests/GraphQL/SchemaTest.php
- `Plugin\Api\GraphQL\Type\Definition\DateTimeType#parseLiteral` で DateTime型を返すように修正。
- FormTypeを使った場合は、string -> DateTIme -> string -> DateTime と2回変換が行われてしまうが、仕方ない。
ref #77
=> DateTime型のargsを型変換するように修正

docs/_config.yml, docs/_data/navigation.yml, docs/_pages/authZ_code_grant.md, docs/_pages/customize/allow_list.md, docs/_pages/customize/query.md, docs/_pages/index.md, docs/_pages/mutation/product_stock.md, docs/_pages/mutation/update_shipped.md, docs/_pages/query/customers.md, docs/_pages/query/orders.md, docs/_pages/query/products.md, docs/_pages/schema.md, docs/assets/css/main.scss
- doc4.ec-cube.net  と同じテーマを remote_theme に設定しました
- 目次をつけて見やすくする
- YAML front matter を最小限に
=> doc4.ec-cube.net のテーマに合わせる

docs/_pages/index.md
4.0.5以降ではブランチの切り替えが必要なくなったのでドキュメントを修正
=> 4.0.5以降ではブランチの切り替えが必要なくなったのでドキュメントを修正

.travis.yml, DependencyInjection/ApiExtension.php, GraphQL/Mutation/UpdateProductStockMutation.php, GraphQL/Mutation/UpdateShippedMutation.php, GraphQL/Query/SearchFormQuery.php, Resource/config/services.yaml, Resource/locale/messages.en.yaml, Resource/locale/messages.ja.yaml, Tests/GraphQL/Mutation/UpdateProductStockMutationTest.php, Tests/GraphQL/Mutation/UpdateShippedMutationTest.php, Tests/GraphQL/SchemaTest.php, Tests/GraphQL/TypesTest.php, Tests/Service/WebHookServiceTest.php, Tests/Web/Admin/LoginControllerTest.php, Tests/Web/Admin/OAuthControllerTest.php, Tests/Web/ApiControllerTest.php, composer.json
- ~~4.1 ブランチでプラグインの `@Route` アノテーションを認識してくれない~~
- [4.1 では self::$container を使用する必要がある](https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing)
- ~~4.0 と 4.1 のユニットテストを両立させる術が無いかも~~ [kiy0taka/eccube4-test-fixer](https://packagist.org/packages/kiy0taka/eccube4-test-fixer) を使用することで解決
=> EC-CUBE4.1対応

Resource/locale/messages.en.yaml, Resource/locale/messages.ja.yaml, Resource/template/admin/OAuth/index.twig
close #95
OAuth管理にエンドポイントをコピーできる機能を追加しました。
クライアントIDをコピーするのと同じUIでコピーできます。
=> エンドポイントをコピーできる機能の追加

Service/WebHookService.php
close #101
サブリクエストでも通知が飛んでしまっていたためフロント画面アクセス時に create が複数回飛ぶような状況となっていました。
マスターリクエストのみ通知するように修正しました。
=> Webhook では MasterRequest のみ通知する

EventListener/AuthorizationRequestResolveListener.php, Service/WebHookService.php
Symfony5.3からdeprecatedで6.0からremoveになるgetMasterRequestを変更しました
=> Symfony5.3からdeprecatedなgetMasterRequestをgetMainRequestに変更

.github/workflows/main.yml, Controller/Admin/OAuthController.php, EventListener/UserResolveListener.php, Form/Type/Admin/ClientType.php, Resource/config/services.yaml, Resource/locale/messages.en.yaml, Resource/locale/messages.ja.yaml, Resource/template/admin/OAuth/edit.twig, Tests/Web/Admin/OAuth2Bundle/AuthorizationControllerTest.php, Tests/Web/OAuth2Bundle/TokenControllerWithROPCTest.php
refs https://github.com/EC-CUBE/next-poc/issues/57
-  grant_type=password の場合は client_secret に  null を設定できるようにする
=> Support grant_type=password

GraphQL/Mutation/AbstractMutation.php, GraphQL/Mutation/EntryCustomerMutation.php, Tests/GraphQL/Mutation/EntryCustomerMutationTest.php
以下のようにリクエスト可能
```graphql
mutation entryCustomer($input: entryInput) {
entryCustomer(
input: $input
) {
id
name01
name02
email
postal_code
phone_number
addr01
addr02
Pref {
id,
name
}
}
}
```
```graphql
{
"input":{
"name_name01":"あああ",
"name_name02":"いいい",
"kana_kana01":"アアア",
"kana_kana02":"イイイ",
"company_name":"corp",
"postal_code":"4440426",
"address_addr01":"aaa",
"address_addr02":"222",
"address_pref":5,
"email":"user@example.com",
"plain_password":"password.12345",
"phone_number":"09017576666",
"birth":"2000-01-01T00:00:00+09:00",
"sex":1,
}
}
```
=> Mutation で FormType を InputObjectType 経由で利用できるようにする

Resource/config/services_dev.yaml, Resource/template/admin/OAuth/graphiql.twig, Security/GraphiQLSecurityContext.php
GraphiQL の headers に Customer のアクセストークンを Authorization  header で渡すことで、Customer の Query/Mutation が使用できる
- Member のアクセストークンは未対応
- GraphiQL の headers はリロードすると消えてしまう。 Settings Dialog の `Persist headers` を ON にすると保存できる(が、時折消えてしまう)
=> Support Authorization header in GraphiQL

Controller/ApiController.php, DependencyInjection/ApiExtension.php, Event.php, Tests/Web/ApiControllerTest.php
=> ログアウト機能の作成。

Doctrine/EventSubscriber/EntityListener.php, GraphQL/EntityAccessPolicy.php, Tests/Web/ApiControllerTest.php
スコープ`read:Xxx`をチェックしてEntityの登録/更新/削除を制御するようにしました。
Doctrineのライフサイクルイベントで制御するようにしていますが、`/api`以外のルーティングではすべてを許可するようにしています。
=> Entityの書き込みに対するScope制御

Resource/template/admin/OAuth/graphiql.twig
GraphiQLが動作していないのでReactのバージョンを18に指定しました。
=> GraphiQLが動作していないのでReactのバージョンを18に指定
