.github/workflows/release.yml
以下のプルリクを参考にしました。
refs https://github.com/EC-CUBE/ec-cube/pull/4581
=> GitHub Acrtions にパッケージングスクリプトを追加

.travis.yml, ApiNav.php, Controller/Admin/Setting/System/OAuth2ClientController.php, Form/Type/Admin/ClientType.php, PluginManager.php, Resource/locale/messages.en.yaml, Resource/locale/messages.ja.yaml, Resource/template/admin/Setting/System/oauth.twig, Resource/template/admin/Setting/System/oauth_edit.twig, Tests/Web/Admin/Setting/System/OAuth2ClientControllerTest.php
close #2
以下のPRを移植
https://github.com/EC-CUBE/ec-cube/pull/4613
=> 管理画面にOAuth管理を実装

EventListener/AuthorizationRequestResolveListener.php, Tests/Web/Admin/OAuth2/OAuth2ControllerTest.php
=> redirect_uri を必須にする

Command/DumpSchemaCommand.php, Controller/ApiController.php, GraphQL/Schema.php
`bin/console  eccube:api:dump-schema` でスキーマを出力する。
=> スキーマ出力コマンドを追加

Controller/Admin/OAuthController.php
=> dump関数がコールされてたので削除

Controller/Admin/OAuthController.php, Controller/Admin/WebHookController.php, Controller/ApiController.php
ちょっと気になったのでhttp methodの指定をしました
(理由があって指定してなかったらごめんなさい...)
=> controllerにhttp methodの指定

docs/_pages/index.md
- EC-CUBE本体の PR を変更
- `bin/console` コマンドは略称を使用しないよう修正
=> Quick Start をわかりやすく修正

docs/_pages/authZ_code_grant.md, docs/_pages/index.md
=> Authorization code flow の手順を追記

Controller/Admin/OAuthController.php, Resource/template/admin/OAuth/index.twig
- CSRFトークンチェック
- 削除ツールチップの修正
ref #43
=> OAuth管理画面の細かい修正

Controller/ApiController.php
ref #56 
```
$ curl -XGET -H "Authorization: Bearer ${ACCESS_TOKEN}" \
"http://127.0.0.1:8000/api?query=%7B%20product(id:2)%20%7B%20id,%20name%20%7D%20%7D"
{
"data": {
"product": {
"id": "2",
"name": "チェリーアイスサンド"
}
}
}
```
=> GETリクエストに対応

GraphQL/Query/SearchFormQuery.php, Tests/GraphQL/SchemaTest.php
=> 検索パラメータの型を調整

docs/_pages/index.md, docs/_pages/mutation/product_stock.md, docs/_pages/mutation/update_shipped.md, docs/_pages/query/customers.md, docs/_pages/query/orders.md, docs/_pages/query/products.md
- パラメータの説明や curl での実行例など、もう少し詳しく追記したい
- [GitHub の Explorer](https://developer.github.com/v4/explorer/) みたいなのが欲しい
=> Query のドキュメント叩き台を追加

LICENSE, README.md, docs/_config.yml, docs/_pages/index.md
Docのインストール手順そのままでは動かなかったので修正
Readmeが古かったのでdocの内容で更新
=> ReadmeとDocを更新

docs/_pages/mutation/update_shipped.md
Mutation updateShippedの概要と実行例を追加
refs https://github.com/EC-CUBE/eccube-api4/issues/57
refs https://github.com/EC-CUBE/eccube-api4/pull/64
=> Mutation updateShippedの概要と実行例を追加

docs/_pages/index.md, docs/_pages/schema.md
コマンドやクエリでも取得可能ですが、ドキュメントにあったほうがいいという意見をいただいたので追加しました。
=> スキーマについてのドキュメントを追加

Service/WebHookService.php
=> Fix argument mismatch.

Resource/template/admin/OAuth/graphiql.twig
- 管理画面のデザインに合わせました
- すぐに実行できるよう defaultQuery も追加
=> GraphiQL に管理画面のメニュー,ヘッダ,フッターをつける

docs/_pages/index.md, docs/_pages/webhook.md
=> webhookに関するドキュメントを追加

docs/_pages/index.md
=> 現在のバージョンでの制限事項

composer.json
=> ストアに登録可能なように composer.json 内の name を修正

docs/_pages/index.md, docs/_pages/quickstart.md
ストア経由でインストールが可能となったので、開発者向けのインストールページを分離しました。
また、エンドポイントについての記載を追加しました。
=> 【Doc】ストア経由でインストールが可能となったので、開発者向けのインストールページを分離

GraphQL/Query/SearchFormQuery.php, Tests/GraphQL/SchemaTest.php
page, limit に0を指定した時にシステムエラーとなっていたので、1以上の数字に制限しました。
close #93
=> page, limit を1以上の数字に制限

Resource/config/bundles.php
正常に動作させるためには以下の PR が取り込まれている必要がある
https://github.com/EC-CUBE/ec-cube/pull/5416
=> Resource/config/bundles.php に league/oauth2-server-bundle の設定を追加
